### ISSUE TITLE
CI failure

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1144]
Pr #1137 only changed Windows code, but there was a failure on Linux: https://dev.azure.com/tokio-rs/Tokio/_build/results?buildId=3285&view=logs&jobId=1d2caa1b-9eda-5fa9-8065-e707e1f1df39&taskId=bbcfb676-a49d-595b-00f6-25d1a1fa4bb4&lineStart=183&lineEnd=183&colStart=6&colEnd=36.

Log of the failure:

```log
---- reconnect_udp_socket_receiving stdout ----
thread 'reconnect_udp_socket_receiving' panicked at 'the following expected events were not found: [ExpectEvent { token: Token(2), interests: READABLE }]', tests/util/mod.rs:235:5
stack backtrace:
   0:     0x557c2e3386f4 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x557c2e3386f4 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x557c2e3386f4 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x557c2e3386f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x557c2e353f3c - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x557c2e2efd65 - std::io::Write::write_fmt::hd48b46e5c13c6612
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/io/mod.rs:1412
   6:     0x557c2e3322a1 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::hc4feb234d1aa0439
                               at src/libstd/io/impls.rs:141
   7:     0x557c2e33ab85 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   8:     0x557c2e33ab85 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   9:     0x557c2e33ab85 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
  10:     0x557c2e33a80c - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:207
  11:     0x557c2e33b285 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  12:     0x557c2e33ae22 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  13:     0x557c2e33ad7c - std::panicking::begin_panic_fmt::hecb5f06c798651bd
                               at src/libstd/panicking.rs:335
  14:     0x557c2e2e7448 - udp_socket::util::expect_events::h9e24961bc6d92fac
  15:     0x557c2e2e1558 - core::ops::function::FnOnce::call_once::h9636c7171d59a027
  16:     0x557c2e2f9c5f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h60313ef8cd80fa37
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  17:     0x557c2e33e36a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  18:     0x557c2e31446e - std::panicking::try::h218111062acbd8af
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:271
  19:     0x557c2e31446e - std::panic::catch_unwind::hb43bd7e3eefd561b
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:394
  20:     0x557c2e31446e - test::run_test::run_test_inner::{{closure}}::h61999fd5b32b527c
                               at src/libtest/lib.rs:1413
  21:     0x557c2e2ef4d5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h94f0165e3063a572
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/sys_common/backtrace.rs:126
  22:     0x557c2e2f36d5 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::ha13ef4f272e8d7f5
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/mod.rs:470
  23:     0x557c2e2f36d5 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4be9743fa104fe58
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:315
  24:     0x557c2e2f36d5 - std::panicking::try::do_call::hc01172ae30fe685a
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:292
  25:     0x557c2e33e36a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  26:     0x557c2e2f3c42 - std::panicking::try::h28c280234b112988
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:271
  27:     0x557c2e2f3c42 - std::panic::catch_unwind::h80abb9ed16b7a343
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panic.rs:394
  28:     0x557c2e2f3c42 - std::thread::Builder::spawn_unchecked::{{closure}}::h079ad7fe053e2851
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/thread/mod.rs:469
  29:     0x557c2e2f3c42 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h66965f502b707a1a
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ops/function.rs:227
  30:     0x557c2e32ecdf - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h483711add4ba2330
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  31:     0x557c2e33da30 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7605b45eb29ed0be
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
  32:     0x557c2e33da30 - std::sys_common::thread::start_thread::h557b0c2dc4449562
                               at src/libstd/sys_common/thread.rs:13
  33:     0x557c2e33da30 - std::sys::unix::thread::Thread::new::thread_start::h7c2a7f9b68fe4bba
                               at src/libstd/sys/unix/thread.rs:79
  34:     0x7fc33fe9a6ba - start_thread
  35:     0x7fc33f9b841d - clone
  36:                0x0 - <unknown>


failures:
    reconnect_udp_socket_receiving
```

**Comment by Thomasdezeeuw** [comment]
I haven't seen this failure any more, so I'm going to close it.
