### ISSUE TITLE
0.7 test fails on s390x

### ISSUE THREAD

**Issue by elmarco** [tokio-rs/mio#1308]
While trying to package mio-0.7 for fedora rawhide, it fails to pass the test: https://kojipkgs.fedoraproject.org//work/tasks/5377/43905377/build.log

```
test tcp_listener_ipv6 ... FAILED
failures:
---- tcp_listener_ipv6 stdout ----
thread 'tcp_listener_ipv6' panicked at 'the following expected events were not found: [ExpectEvent { token: Token(0), readiness: Readiness(1) }]', tests/util/mod.rs:158:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    tcp_listener_ipv6
```

and

```
test tcp_stream_ipv6 ... FAILED
failures:
---- tcp_stream_ipv6 stdout ----
thread 'tcp_stream_ipv6' panicked at 'the following expected events were not found: [ExpectEvent { token: Token(0), readiness: Readiness(1) }]', tests/util/mod.rs:158:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    tcp_stream_ipv6
```

**Comment by Thomasdezeeuw** [comment]
Could you rerun this with `RUST_BACKTRACE` set to `1` or `full`? Currently we don't really have enough information to debug this.

Btw I would recommand running all tests on any CI with the `RUST_BACKTRACE` env var set for any rust projects to get a more detailed error log and backtrace.

**Comment by elmarco** [comment]
I enabled `RUST_BACKTRACE` and it disappeared. Probably random bug, feel free to close if I can't provide more details.

**Comment by ignatenkobrain** [comment]
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }', tests/tcp_listener.rs:279:24
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_none_failed
   9: core::result::Result<T,E>::unwrap
             at /builddir/build/BUILD/rustc-1.43.0-src/src/libcore/result.rs:1003
  10: tcp_listener::start_connections::{{closure}}
             at tests/tcp_listener.rs:279
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test no_events_after_deregister ... FAILED
test tcp_listener_std ... ok
test tcp_listener_two_streams ... ok
test tcp_listener_ipv6 ... FAILED
failures:
---- no_events_after_deregister stdout ----
thread 'no_events_after_deregister' panicked at 'unable to accept connection: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', tests/tcp_listener.rs:204:34
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
   4: std::panicking::default_hook::{{closure}}
   5: std::panicking::default_hook
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_none_failed
  10: core::result::Result<T,E>::expect
             at /builddir/build/BUILD/rustc-1.43.0-src/src/libcore/result.rs:961
  11: tcp_listener::no_events_after_deregister
             at tests/tcp_listener.rs:204
  12: tcp_listener::no_events_after_deregister::{{closure}}
             at tests/tcp_listener.rs:186
  13: core::ops::function::FnOnce::call_once
             at /builddir/build/BUILD/rustc-1.43.0-src/src/libcore/ops/function.rs:232
  14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  15: __rust_try
  16: __rust_maybe_catch_panic
  17: test::run_test::run_test_inner::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
---- tcp_listener_ipv6 stdout ----
thread 'tcp_listener_ipv6' panicked at 'the following expected events were not found: [ExpectEvent { token: Token(0), readiness: Readiness(1) }]', tests/util/mod.rs:158:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
   4: std::panicking::default_hook::{{closure}}
   5: std::panicking::default_hook
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: std::panicking::begin_panic_fmt
   9: tcp_listener::util::expect_events
             at tests/util/mod.rs:158
  10: tcp_listener::smoke_test_tcp_listener
             at tests/tcp_listener.rs:68
  11: tcp_listener::tcp_listener_ipv6
             at tests/tcp_listener.rs:35
  12: tcp_listener::tcp_listener_ipv6::{{closure}}
             at tests/tcp_listener.rs:34
  13: core::ops::function::FnOnce::call_once
             at /builddir/build/BUILD/rustc-1.43.0-src/src/libcore/ops/function.rs:232
  14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  15: __rust_try
  16: __rust_maybe_catch_panic
  17: test::run_test::run_test_inner::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
failures:
    no_events_after_deregister
    tcp_listener_ipv6
```

**Comment by Thomasdezeeuw** [comment]
Both tests fail (I think) on the same issue: connection to the listener in [`start_connections`](https://github.com/tokio-rs/mio/blob/976f2354d0e8fbbb64fba3bf017d7131f9c369a0/tests/tcp_listener.rs#L272-L284). Maybe the thread that gets started never gets a chance to run?

Could you try running using only a single test thread:

```bash
RUST_BACKTRACE=full cargo test --all-features -- --test-threads=1
```

**Comment by Thomasdezeeuw** [comment]
@elmarco @ignatenkobrain any update on this?

**Comment by Thomasdezeeuw** [comment]
Closing due to inactivity.
