### ISSUE TITLE
TCP connect_error test is flaky on macOS

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1332]
The last call to `expect_no_events` might be too strict: https://github.com/tokio-rs/mio/blob/68805cbeb7797e0d2653e861e009cc10c05bd4f9/tests/tcp.rs#L578

Error log and backtrace:

```log
---- connect_error stdout ----
[ERROR tcp::util] unexpected event: Event { token: Token(0), readable: false, writable: true, error: false, read_closed: false, write_closed: true, priority: false, aio: false, lio: false }
thread 'connect_error' panicked at 'received events, but didn't expect any, see above', tests/util/mod.rs:172:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at /rustc/feb3536eba10c2e4585d066629598f03d5ddc7c6/src/libstd/io/mod.rs:1537
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:176
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  12: std::panicking::begin_panic
             at src/libcore/alloc/layout.rs:363
  13: tcp::util::expect_no_events
             at tests/util/mod.rs:172
  14: tcp::connect_error
             at tests/tcp.rs:578
  15: tcp::connect_error::{{closure}}
             at tests/tcp.rs:544
  16: core::ops::function::FnOnce::call_once
             at /Users/thomas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  17: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/feb3536eba10c2e4585d066629598f03d5ddc7c6/src/liballoc/boxed.rs:1076
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/feb3536eba10c2e4585d066629598f03d5ddc7c6/src/libstd/panic.rs:318
  19: std::panicking::try::do_call
             at /rustc/feb3536eba10c2e4585d066629598f03d5ddc7c6/src/libstd/panicking.rs:297
  20: std::panicking::try
             at /rustc/feb3536eba10c2e4585d066629598f03d5ddc7c6/src/libstd/panicking.rs:274
  21: std::panic::catch_unwind
             at /rustc/feb3536eba10c2e4585d066629598f03d5ddc7c6/src/libstd/panic.rs:394
  22: test::run_test_in_process
             at src/libtest/lib.rs:541
  23: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Thomasdezeeuw** [comment]
CI failure backtrace from #1374:

```log
---- connect_error stdout ----
[ERROR tcp::util] unexpected event: Event { token: Token(0), readable: false, writable: true, error: false, read_closed: false, write_closed: true, priority: false, aio: false, lio: false }
thread 'main' panicked at 'received events, but didn't expect any, see above', tests/util/mod.rs:172:9
stack backtrace:
   0:        0x104a747d4 - std::backtrace_rs::backtrace::libunwind::trace::h93742dd1b3bd2027
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:        0x104a747d4 - std::backtrace_rs::backtrace::trace_unsynchronized::h811523dd305c9cc6
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:        0x104a747d4 - std::sys_common::backtrace::_print_fmt::h648a1661b958f275
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
   3:        0x104a747d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4b962ed89f71a03
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
   4:        0x104a96380 - core::fmt::write::h94ae1e793baa7a00
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
   5:        0x104a00bf9 - std::io::Write::write_fmt::h157f47fae3a98513
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
   6:        0x104a6bc0c - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h07fb32b0b84e660e
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/impls.rs:176
   7:        0x104a76a05 - std::sys_common::backtrace::_print::he99526f3d58c4f6f
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
   8:        0x104a76a05 - std::sys_common::backtrace::print::h18711c06562fe387
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
   9:        0x104a76a05 - std::panicking::default_hook::{{closure}}::hc6119c7d16548caf
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
  10:        0x104a766f8 - std::panicking::default_hook::heae8b62897b351dc
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:216
  43:        0x1049e3ca1 - std::rt::lang_start::h6ba0c9bfb1e2d367
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:65
  44:        0x1049d0b72 - _main

```
