### ISSUE TITLE
tcp_reset_close_event test failed on Windows CI 

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1340]
https://dev.azure.com/tokio-rs/Tokio/_build/results?buildId=6122&view=logs&jobId=429a383f-e486-57ac-3982-9ac65641a32a&j=429a383f-e486-57ac-3982-9ac65641a32a&t=34887100-476e-568c-c947-304a658b3e9f, log:

```log
---- tcp_reset_close_event stdout ----
thread 'tcp_reset_close_event' panicked at 'the following expected events were not found: [ExpectEvent { token: Token(0), readiness: Readiness(32) }]', tests\util\mod.rs:158:5
stack backtrace:
   0:   0x23de7d - core::fmt::write
                       at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\fmt\mod.rs:1069
   1:   0x19f487 - std::io::Write::write_fmt<test::helpers::sink::Sink>
                       at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libstd\io\mod.rs:1504
   2:   0x217b3c - std::io::impls::{{impl}}::write_fmt<Write>
                       at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\io\impls.rs:156
   3:   0x22573a - std::sys_common::backtrace::_print
   4:   0x22573a - std::sys_common::backtrace::print
   5:   0x22573a - std::panicking::default_hook::{{closure}}
                       at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:198
   6:   0x2252e1 - std::panicking::default_hook
                       at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:215
   7:   0x225dca - std::panicking::rust_panic_with_hook
                       at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:511
   8:   0x2259e8 - std::panicking::begin_panic_handler
                       at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:419
   9:   0x225943 - std::panicking::begin_panic_fmt
                       at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:373
  10:   0x15b3d6 - tcp_stream::util::expect_events
                       at D:\a\1\s\tests\util\mod.rs:158
  11:   0x17a916 - tcp_stream::tcp_reset_close_event
                       at D:\a\1\s\tests\tcp_stream.rs:639
  12:   0x168dbd - tcp_stream::tcp_reset_close_event::{{closure}}
                       at D:\a\1\s\tests\tcp_stream.rs:613
  13:   0x15ca12 - core::ops::function::FnOnce::call_once<closure-0,()>
                       at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libcore\ops\function.rs:232
  14:   0x1c7c8e - alloc::boxed::{{impl}}::call_once
                       at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\liballoc\boxed.rs:1008
    tcp_reset_close_event

test result: FAILED. 14 passed; 1 failed; 4 ignored; 0 measured; 0 filtered out
```

**Comment by Thomasdezeeuw** [comment]
Haven't seen this issue anymore.
