### ISSUE TITLE
Test no_events_after_deregister failed on CI

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1376]
While testing pr #1374. Log from https://dev.azure.com/tokio-rs/Tokio/_build/results?buildId=6371&view=logs&jobId=9ee66ee0-c6b6-50f2-32c8-2bebb82e1137&j=9ee66ee0-c6b6-50f2-32c8-2bebb82e1137&t=3b0adf12-f909-59d8-0849-13de19d8dc87, https://dev.azure.com/tokio-rs/e4c287c8-f114-46bc-a72c-9560911d83d6/_apis/build/builds/6371/logs/124.

```log
2020-10-20T19:34:07.9648420Z      Running target/debug/deps/tcp_stream-f2065a7326483e90
2020-10-20T19:34:08.0146140Z 
2020-10-20T19:34:08.0147600Z running 21 tests
2020-10-20T19:34:08.0148000Z test is_send_and_sync ... ok
2020-10-20T19:34:08.0159220Z test get_ttl_without_previous_set ... ok
2020-10-20T19:34:08.0176430Z thread '<unnamed>' panicked at 'error reading: Os { code: 9, kind: Other, message: "Bad file descriptor" }', tests/tcp_stream.rs:714:22
2020-10-20T19:34:08.0181250Z test get_nodelay_without_previous_set ... ok
2020-10-20T19:34:08.0181930Z test hup_event_on_disconnect ... ok
2020-10-20T19:34:08.0182300Z stack backtrace:
2020-10-20T19:34:08.0182660Z test reregistering ... ok
2020-10-20T19:34:08.0182970Z test raw_fd ... ok
2020-10-20T19:34:08.0183260Z test set_get_nodelay ... ok
2020-10-20T19:34:08.0183880Z test set_get_ttl ... ok
2020-10-20T19:34:08.0184200Z test shutdown_both ... ok
2020-10-20T19:34:08.0184650Z test shutdown_write ... ignored
2020-10-20T19:34:08.0184990Z test shutdown_read ... ok
2020-10-20T19:34:08.0189910Z test tcp_shutdown_client_both_close_event ... ok
2020-10-20T19:34:08.0193920Z test tcp_shutdown_client_read_close_event ... ok
2020-10-20T19:34:08.0197380Z test tcp_shutdown_client_write_close_event ... ok
2020-10-20T19:34:08.0201530Z test tcp_shutdown_server_write_close_event ... ok
2020-10-20T19:34:08.0207240Z test tcp_stream_ipv4 ... ok
2020-10-20T19:34:08.0213470Z test tcp_stream_ipv6 ... ok
2020-10-20T19:34:08.0219510Z test tcp_stream_std ... ok
2020-10-20T19:34:08.0308550Z    0:        0x10f65fe84 - std::backtrace_rs::backtrace::libunwind::trace::h93742dd1b3bd2027
2020-10-20T19:34:08.0309400Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
2020-10-20T19:34:08.0310640Z    1:        0x10f65fe84 - std::backtrace_rs::backtrace::trace_unsynchronized::h811523dd305c9cc6
2020-10-20T19:34:08.0311440Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
2020-10-20T19:34:08.0312830Z    2:        0x10f65fe84 - std::sys_common::backtrace::_print_fmt::h648a1661b958f275
2020-10-20T19:34:08.0313620Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
2020-10-20T19:34:08.0314820Z    3:        0x10f65fe84 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4b962ed89f71a03
2020-10-20T19:34:08.0315650Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
2020-10-20T19:34:08.0317260Z    4:        0x10f680f50 - core::fmt::write::h94ae1e793baa7a00
2020-10-20T19:34:08.0317930Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
2020-10-20T19:34:08.0318900Z    5:        0x10f65932b - std::io::Write::write_fmt::h5c716758fdc3057f
2020-10-20T19:34:08.0319570Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
2020-10-20T19:34:08.0320570Z    6:        0x10f6620b5 - std::sys_common::backtrace::_print::he99526f3d58c4f6f
2020-10-20T19:34:08.0321320Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
2020-10-20T19:34:08.0322330Z    7:        0x10f6620b5 - std::sys_common::backtrace::print::h18711c06562fe387
2020-10-20T19:34:08.0323050Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
2020-10-20T19:34:08.0324080Z    8:        0x10f6620b5 - std::panicking::default_hook::{{closure}}::hc6119c7d16548caf
2020-10-20T19:34:08.0324790Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
2020-10-20T19:34:08.0325910Z    9:        0x10f661df7 - std::panicking::default_hook::heae8b62897b351dc
2020-10-20T19:34:08.0326850Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
2020-10-20T19:34:08.0327910Z   10:        0x10f662655 - std::panicking::rust_panic_with_hook::hc36596b4257bea99
2020-10-20T19:34:08.0328620Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
2020-10-20T19:34:08.0329650Z   11:        0x10f6621eb - std::panicking::begin_panic_handler::{{closure}}::h49e5ddc3f21ca2fb
2020-10-20T19:34:08.0330380Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
2020-10-20T19:34:08.0331430Z   12:        0x10f6602f8 - std::sys_common::backtrace::__rust_end_short_backtrace::h9bd32c9ad3fad18f
2020-10-20T19:34:08.0332190Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
2020-10-20T19:34:08.0333090Z   13:        0x10f6621aa - rust_begin_unwind
2020-10-20T19:34:08.0333850Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
2020-10-20T19:34:08.0334900Z   14:        0x10f68950f - core::panicking::panic_fmt::hcdc9362d34d55302
2020-10-20T19:34:08.0335620Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
2020-10-20T19:34:08.0336620Z   15:        0x10f689415 - core::option::expect_none_failed::hef0458611b13747b
2020-10-20T19:34:08.0337270Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
2020-10-20T19:34:08.0338220Z   16:        0x10f5b802a - core::result::Result<T,E>::expect::hab418f281f4ad284
2020-10-20T19:34:08.0338960Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/result.rs:933
2020-10-20T19:34:08.0340090Z   17:        0x10f5cd124 - tcp_stream::echo_listener::{{closure}}::h7a1b6363b20d9627
2020-10-20T19:34:08.0340740Z                                at /Users/runner/work/1/s/tests/tcp_stream.rs:705
2020-10-20T19:34:08.0341850Z   18:        0x10f5b2d91 - std::sys_common::backtrace::__rust_begin_short_backtrace::hacb1699b2b4a7bc2
2020-10-20T19:34:08.0342660Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:137
2020-10-20T19:34:08.0343880Z   19:        0x10f5ad101 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hb274ec69decf700f
2020-10-20T19:34:08.0345050Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/mod.rs:458
2020-10-20T19:34:08.0347100Z   20:        0x10f5b2c31 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h213c4238043c8e6b
2020-10-20T19:34:08.0347990Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:308
2020-10-20T19:34:08.0349140Z   21:        0x10f5b5405 - std::panicking::try::do_call::hf9215199b8a27ef2
2020-10-20T19:34:08.0349840Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
2020-10-20T19:34:08.0351250Z   22:        0x10f5b552d - ___rust_try
2020-10-20T19:34:08.0352170Z   23:        0x10f5b52b1 - std::panicking::try::he2365aec59cb4547
2020-10-20T19:34:08.0352930Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
2020-10-20T19:34:08.0353950Z   24:        0x10f5b2cb1 - std::panic::catch_unwind::h0edeceeb99c5cc7b
2020-10-20T19:34:08.0354680Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
2020-10-20T19:34:08.0355810Z   25:        0x10f5acc50 - std::thread::Builder::spawn_unchecked::{{closure}}::h0b0b83fd6548a5a9
2020-10-20T19:34:08.0356610Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/mod.rs:457
2020-10-20T19:34:08.0357730Z   26:        0x10f5a83c1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdc94ca33386885b6
2020-10-20T19:34:08.0358730Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
2020-10-20T19:34:08.0359940Z   27:        0x10f6697cd - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h755d7a92e05e8478
2020-10-20T19:34:08.0360840Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
2020-10-20T19:34:08.0361980Z   28:        0x10f6697cd - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h8f75d00685aca963
2020-10-20T19:34:08.0362840Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
2020-10-20T19:34:08.0363920Z   29:        0x10f6697cd - std::sys::unix::thread::Thread::new::thread_start::hd4805e9612a32deb
2020-10-20T19:34:08.0364740Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/unix/thread.rs:87
2020-10-20T19:34:08.0390430Z   30:     0x7fff6e506109 - __pthread_start
2020-10-20T19:34:08.0886410Z test registering ... ok
2020-10-20T19:34:08.0913650Z test no_events_after_deregister ... FAILED
2020-10-20T19:34:08.1196440Z test tcp_reset_close_event ... ok
2020-10-20T19:34:08.1197200Z 
2020-10-20T19:34:08.1197580Z failures:
2020-10-20T19:34:08.1197820Z 
2020-10-20T19:34:08.1198900Z ---- no_events_after_deregister stdout ----
2020-10-20T19:34:08.1200020Z thread 'no_events_after_deregister' panicked at 'unexpected OK result, expected a `WouldBlock` error', tests/util/mod.rs:193:18
2020-10-20T19:34:08.1200600Z stack backtrace:
2020-10-20T19:34:08.1201520Z    0:        0x10f65fe84 - std::backtrace_rs::backtrace::libunwind::trace::h93742dd1b3bd2027
2020-10-20T19:34:08.1202290Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
2020-10-20T19:34:08.1203860Z    1:        0x10f65fe84 - std::backtrace_rs::backtrace::trace_unsynchronized::h811523dd305c9cc6
2020-10-20T19:34:08.1204750Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
2020-10-20T19:34:08.1205930Z    2:        0x10f65fe84 - std::sys_common::backtrace::_print_fmt::h648a1661b958f275
2020-10-20T19:34:08.1206660Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
2020-10-20T19:34:08.1207920Z    3:        0x10f65fe84 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4b962ed89f71a03
2020-10-20T19:34:08.1209130Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
2020-10-20T19:34:08.1210240Z    4:        0x10f680f50 - core::fmt::write::h94ae1e793baa7a00
2020-10-20T19:34:08.1210890Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
2020-10-20T19:34:08.1212060Z    5:        0x10f5ec199 - std::io::Write::write_fmt::h157f47fae3a98513
2020-10-20T19:34:08.1212730Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
2020-10-20T19:34:08.1213940Z    6:        0x10f65724c - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h07fb32b0b84e660e
2020-10-20T19:34:08.1214780Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/impls.rs:176
2020-10-20T19:34:08.1215900Z    7:        0x10f6620b5 - std::sys_common::backtrace::_print::he99526f3d58c4f6f
2020-10-20T19:34:08.1216610Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
2020-10-20T19:34:08.1217780Z    8:        0x10f6620b5 - std::sys_common::backtrace::print::h18711c06562fe387
2020-10-20T19:34:08.1218450Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
2020-10-20T19:34:08.1219800Z    9:        0x10f6620b5 - std::panicking::default_hook::{{closure}}::hc6119c7d16548caf
2020-10-20T19:34:08.1220520Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
2020-10-20T19:34:08.1221660Z   10:        0x10f661da8 - std::panicking::default_hook::heae8b62897b351dc
2020-10-20T19:34:08.1222350Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:216
2020-10-20T19:34:08.1223460Z   11:        0x10f662655 - std::panicking::rust_panic_with_hook::hc36596b4257bea99
2020-10-20T19:34:08.1224160Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
2020-10-20T19:34:08.1225310Z   12:        0x10f6389d4 - std::panicking::begin_panic::{{closure}}::h8324661588d26d31
2020-10-20T19:34:08.1226020Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:498
2020-10-20T19:34:08.1227180Z   13:        0x10f638918 - std::sys_common::backtrace::__rust_end_short_backtrace::hbff9058507eb5ce4
2020-10-20T19:34:08.1227940Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
2020-10-20T19:34:08.1229030Z   14:        0x10f687ff2 - std::panicking::begin_panic::hf49eddb82d2deb93
2020-10-20T19:34:08.1229730Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:497
2020-10-20T19:34:08.1230840Z   15:        0x10f5c65db - tcp_stream::util::assert_would_block::h57a0785a1c6f9663
2020-10-20T19:34:08.1231470Z                                at /Users/runner/work/1/s/tests/util/mod.rs:193
2020-10-20T19:34:08.1232510Z   16:        0x10f5bf3d5 - tcp_stream::no_events_after_deregister::hfbe3aabbb03e0bdb
2020-10-20T19:34:08.1233150Z                                at /Users/runner/work/1/s/tests/tcp_stream.rs:496
2020-10-20T19:34:08.1234210Z   17:        0x10f5cdb41 - tcp_stream::no_events_after_deregister::{{closure}}::hf28006bb5561a154
2020-10-20T19:34:08.1234880Z                                at /Users/runner/work/1/s/tests/tcp_stream.rs:474
2020-10-20T19:34:08.1235900Z   18:        0x10f5a87e1 - core::ops::function::FnOnce::call_once::h9ffbcd7cfa0202fb
2020-10-20T19:34:08.1236610Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
2020-10-20T19:34:08.1238060Z   19:        0x10f612d6a - core::ops::function::FnOnce::call_once::h9391ab3b783df913
2020-10-20T19:34:08.1238770Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
2020-10-20T19:34:08.1239800Z   20:        0x10f612d6a - test::__rust_begin_short_backtrace::h3525a66645c5bfc7
2020-10-20T19:34:08.1240550Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/test/src/lib.rs:517
2020-10-20T19:34:08.1241670Z   21:        0x10f6115de - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hb53c7c20f4b697da
2020-10-20T19:34:08.1242490Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
2020-10-20T19:34:08.1243640Z   22:        0x10f6115de - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0f88e6632cbcaf45
2020-10-20T19:34:08.1244480Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:308
2020-10-20T19:34:08.1245480Z   23:        0x10f6115de - std::panicking::try::do_call::h176cd5bbf9c3e233
2020-10-20T19:34:08.1246220Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
2020-10-20T19:34:08.1247230Z   24:        0x10f6115de - std::panicking::try::h9e191965ecb064f2
2020-10-20T19:34:08.1247950Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
2020-10-20T19:34:08.1249140Z   25:        0x10f6115de - std::panic::catch_unwind::he0e9a2bd3a4985c5
2020-10-20T19:34:08.1249860Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
2020-10-20T19:34:08.1250850Z   26:        0x10f6115de - test::run_test_in_process::h9a942859b5f42741
2020-10-20T19:34:08.1251570Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/test/src/lib.rs:544
2020-10-20T19:34:08.1252630Z   27:        0x10f6115de - test::run_test::run_test_inner::{{closure}}::h2b2c6792a791ad99
2020-10-20T19:34:08.1253390Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/test/src/lib.rs:450
2020-10-20T19:34:08.1254460Z   28:        0x10f5eb60b - std::sys_common::backtrace::__rust_begin_short_backtrace::h25e344bd33c2e044
2020-10-20T19:34:08.1255320Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:137
2020-10-20T19:34:08.1256460Z   29:        0x10f5f09a5 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h1df590fc75789c40
2020-10-20T19:34:08.1257280Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/mod.rs:458
2020-10-20T19:34:08.1258430Z   30:        0x10f5f09a5 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb26fa88f094f6563
2020-10-20T19:34:08.1259270Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:308
2020-10-20T19:34:08.1260270Z   31:        0x10f5f09a5 - std::panicking::try::do_call::h4630d34ae943c961
2020-10-20T19:34:08.1261010Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
2020-10-20T19:34:08.1261990Z   32:        0x10f5f09a5 - std::panicking::try::h4de3d4e25424c7a7
2020-10-20T19:34:08.1262710Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
2020-10-20T19:34:08.1263710Z   33:        0x10f5f09a5 - std::panic::catch_unwind::h61a47ec7c8f07fea
2020-10-20T19:34:08.1264430Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
2020-10-20T19:34:08.1265500Z   34:        0x10f5f09a5 - std::thread::Builder::spawn_unchecked::{{closure}}::hee86f0ef2df623b6
2020-10-20T19:34:08.1266280Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/mod.rs:457
2020-10-20T19:34:08.1267700Z   35:        0x10f5f09a5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h002c6dc1d62df3bc
2020-10-20T19:34:08.1268510Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
2020-10-20T19:34:08.1269650Z   36:        0x10f6697cd - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h755d7a92e05e8478
2020-10-20T19:34:08.1270480Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
2020-10-20T19:34:08.1271610Z   37:        0x10f6697cd - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h8f75d00685aca963
2020-10-20T19:34:08.1272520Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
2020-10-20T19:34:08.1273610Z   38:        0x10f6697cd - std::sys::unix::thread::Thread::new::thread_start::hd4805e9612a32deb
2020-10-20T19:34:08.1274450Z                                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/unix/thread.rs:87
2020-10-20T19:34:08.1275380Z   39:     0x7fff6e506109 - __pthread_start
2020-10-20T19:34:08.1275740Z 
2020-10-20T19:34:08.1276060Z 
2020-10-20T19:34:08.1276340Z failures:
2020-10-20T19:34:08.1276700Z     no_events_after_deregister
2020-10-20T19:34:08.1277070Z 
2020-10-20T19:34:08.1277490Z test result: FAILED. 19 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out
2020-10-20T19:34:08.1278160Z 
2020-10-20T19:34:08.1278920Z error: test failed, to rerun pass '--test tcp_stream'
```

**Comment by Thomasdezeeuw** [comment]
Consider this is a bad fd error I think this was solved by https://github.com/tokio-rs/mio/pull/1498.
