### ISSUE TITLE
SocketAddr  attempt to subtract with overflow

### ISSUE THREAD

**Issue by WalterSmuts** [tokio-rs/mio#1403]
I think there might be an issue [here](https://github.com/tokio-rs/mio/blob/master/src/sys/unix/uds/socketaddr.rs#L29-L45):
```
    fn address(&self) -> AddressKind<'_> {
        let offset = path_offset(&self.sockaddr);
        let len = self.socklen as usize - offset;
        let path = unsafe { &*(&self.sockaddr.sun_path as *const [libc::c_char] as *const [u8]) };

        // macOS seems to return a len of 16 and a zeroed sun_path for unnamed addresses
        if len == 0
            || (cfg!(not(any(target_os = "linux", target_os = "android")))
                && self.sockaddr.sun_path[0] == 0)
        {
            AddressKind::Unnamed
        } else if self.sockaddr.sun_path[0] == 0 {
            AddressKind::Abstract(&path[1..len])
        } else {
            AddressKind::Pathname(OsStr::from_bytes(&path[..len - 1]).as_ref())
        }
    }
```
From the [linux man pages for "recv"](https://man7.org/linux/man-pages/man2/recv.2.html):
```
   recvfrom()
       recvfrom() places the received message into the buffer buf.  The
       caller must specify the size of the buffer in len.

       If src_addr is not NULL, and the underlying protocol provides the
       source address of the message, that source address is placed in the
       buffer pointed to by src_addr.  In this case, addrlen is a value-re‐
       sult argument.  Before the call, it should be initialized to the size
       of the buffer associated with src_addr.  Upon return, addrlen is up‐
       dated to contain the actual size of the source address.  The returned
       address is truncated if the buffer provided is too small; in this
       case, addrlen will return a value greater than was supplied to the
       call.
```
Specifically this part `Upon return, addrlen is updated to contain the actual size of the source address`. I believe if the related socket is not bound to an address, i.e. the value for `self.socklen` would be set to `0`, you would get an error, because in the following line you'd be subtracting some positive value (in my case `2`) from `0`:
```
        let len = self.socklen as usize - offset;
```
Resulting in the following runtime error:
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/ANT.AMAZON.COM/wssmts/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.6/src/sys/unix/uds/socketaddr.rs:31:19
```

**Comment by Thomasdezeeuw** [comment]
I think in `SocketAddr::address` we would need to check for `self.socklen == 0` and return `AddressKind::Unnamed` instead, or maybe `None`?

@WalterSmuts do you have a small example we can use as test?

**Comment by WalterSmuts** [comment]
> do you have a small example we can use as test?

Here's the [git repo](https://github.com/WalterSmuts/minimal-socket-addr-error-example).
And here's a summary:
```
use mio::net::UnixDatagram;
use std::path::Path;

fn main() {
    let mut buff = [0u8; 1024];
    let path = Path::new("/tmp/arbitrary.sock");
    let socket_a = UnixDatagram::bind(path).unwrap();
    let socket_b = UnixDatagram::unbound().unwrap();

    socket_b.connect(path).unwrap();
    socket_b.send_to(&buff, path).unwrap();

    let (_size, addr) = socket_a.recv_from(&mut buff).unwrap();
    let _ = addr.as_pathname();
}
```
Produces output:
```
wssmts@laptop:~/Programs/minimal-socket-addr-error-example > cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/minimal-socket-addr-error-example`
thread 'main' panicked at 'attempt to subtract with overflow', /home/ANT.AMAZON.COM/wssmts/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.6/src/sys/unix/uds/socketaddr.rs:31:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
