### ISSUE TITLE
Flaky no_events_after_deregister test

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1421]
Log:

```

---- no_events_after_deregister stdout ----
thread '<unnamed>' panicked at 'error reading: Os { code: 9, kind: Other, message: "Bad file descriptor" }', tests/tcp_stream.rs:718:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::expect
             at /Users/thomas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:933:23
   4: tcp_stream::echo_listener::{{closure}}
             at ./tests/tcp_stream.rs:709:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'no_events_after_deregister' panicked at 'unexpected OK result, expected a `WouldBlock` error', tests/util/mod.rs:193:18
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/thomas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: tcp_stream::util::assert_would_block
             at ./tests/util/mod.rs:193:18
   2: tcp_stream::no_events_after_deregister
             at ./tests/tcp_stream.rs:496:5
   3: tcp_stream::no_events_after_deregister::{{closure}}
             at ./tests/tcp_stream.rs:474:1
   4: core::ops::function::FnOnce::call_once
             at /Users/thomas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    no_events_after_deregister

test result: FAILED. 19 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.10s

error: test failed, to rerun pass '--test tcp_stream'
error: process didn't exit successfully: `cargo test --manifest-path Cargo.toml --no-default-features --features net,os-ext,os-poll` (exit code: 101)
```

on macOS `cargo test --no-default-features --features net,os-ext,os-poll` reproduces it.

**Comment by Thomasdezeeuw** [comment]
Got the same error for `reregistering`, so it's likely not actually `no_events_after_deregister`.

```log

---- reregistering stdout ----
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Other, message: "Bad file descriptor" }', tests/tcp_stream.rs:706:53
stack backtrace:
   0: rust_begin_unwind
             at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /Users/thomas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: tcp_stream::echo_listener::{{closure}}
             at ./tests/tcp_stream.rs:706:35
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'reregistering' panicked at 'unable to join thread: Any', tests/tcp_stream.rs:470:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::expect
             at /Users/thomas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:933:23
   4: tcp_stream::reregistering
             at ./tests/tcp_stream.rs:470:5
   5: tcp_stream::reregistering::{{closure}}
             at ./tests/tcp_stream.rs:446:1
   6: core::ops::function::FnOnce::call_once
             at /Users/thomas/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/11c94a197726b6a981828cb1837d7c3eed1b841d/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Thomasdezeeuw** [comment]
Found it: https://github.com/tokio-rs/mio/blob/1d9dd13af0ea7ba9d9ffa6af36023ef08604bca0/tests/tcp_stream.rs#L811
